version: "1"
rules:
  - base: master
    upstream: SlimefunGuguProject:master
    mergeMethod: merge
    assignees:
      - ytdd9527
      - balugaq
    conflictReviewers:
      - ytdd9527
      - balugaq

