name: Networks
author: Sefiraat
description: No idea yet
main: io.github.sefiraat.networks.Networks
website: https://github.com/ytdd9527/NetworksExpansion
version: ${project.version}
api-version: 1.20
depend:
  - Slimefun
softdepend:
  - GuizhanLibPlugin
  - InfinityExpansion
  - Netheopoiesis
  - SlimeHUD
  - WildChests
  - RoseStacker
  - WildStacker
  - mcMMO
commands:
  networks:
    description: /networks
    usage: /networks <sub>
