name: Bug Report
description: Report bugs or issues for this plugin
labels: [ "bug" ]
assignees:
  - ytdd9527
  - balugaq
body:
  - type: markdown
    attributes:
      value: |
        ## Welcome to the NetworksExpansion Issue Tracker
        You are reporting a bug in NetworksExpansion.

        <strong><i>You must fill out the fields marked with an asterisk (*)</i></strong>

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Before reporting, you need to confirm
      options:
        - label: You are using the version downloaded from the build site
        - label: You have verified the checksum of the downloaded file to ensure it is fully downloaded
        - label: You have not made any changes to the content of the downloaded file
        - label: You have searched the [list of known issues](https://github.com/SlimefunGuguProject/Networks/issues) and have not found the same issue
          required: true

  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: |
        Describe the issue you want to report in detail
        Providing detailed information can help us process the issue faster
      placeholder: Simply saying "it doesn't work" doesn't help developers to locate the problem.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: |
        Please describe in detail how to reproduce the issue
        If there is a video, please provide the video link here
      placeholder: |
        1. xxx
        2. xxx
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: |
        What you think should happen
        Sometimes, the issue is caused by a misunderstanding of a feature.
    validations:
      required: true

  - type: input
    id: server-log
    attributes:
      label: Server Log
      description: |
        Please check if there are any errors in the server log, and if so, upload them to [https://paste.guizhanss.net/](https://paste.guizhanss.net/) and enter the link here.
        **Do not paste the log directly here**
      placeholder: https://paste.guizhanss.net/...
    validations:
      required: false

  - type: input
    id: error-report
    attributes:
      label: Error Report
      description: |
        If the server log mentions files in `/plugins/Slimefun/error-reports` (i.e., error reports)
        Please upload them to [https://paste.guizhanss.net/](https://paste.guizhanss.net/) and enter the link here.
        **Do not paste the error report directly here**
      placeholder: https://paste.guizhanss.net/...
    validations:
      required: false

  - type: dropdown
    id: server-software
    attributes:
      label: Server Software
      description: Please select the software your server is using
      options:
        - Spigot
        - Paper
        - Purpur
        - Airplane
        - Other (please specify in the issue description)
    validations:
      required: true

  - type: input
    id: minecraft-version
    attributes:
      label: Minecraft Version
      description: Please fill in your Minecraft version
    validations:
      required: true

  - type: textarea
    id: slimefun-version
    attributes:
      label: Slimefun Version
      description: |
        Please fill in the Slimefun version
        (e.g., v4.9-canary-08120db)
        If you have administrative privileges, it is recommended to run the `/sf versions` command, take a screenshot, and upload all the output here.
    validations:
      required: true

  - type: input
    id: version-plugin
    attributes:
      label: Plugin Version
      description: |
        Please fill in the plugin version
    validations:
      required: true
