name: 请求帮助
description: 请求帮助
labels: [ "help wanted" ]
assignees:
  - ytdd9527
  - balugaq
body:
  - type: markdown
    attributes:
      value: |
        ## 欢迎来到 NetworksExpansion 的问题追踪器
        你正在请求帮助以解决 NetworksExpansion 的问题。

        <strong><i>你必须填写标注为星号（*）的表单项</i></strong>

  - type: checkboxes
    id: checklist
    attributes:
      label: 检查项目
      description: 在汇报之前，你需要确认
      options:
        - label: 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/Networks/issues)，且没有找到相同的问题
          required: true

  - type: textarea
    id: description
    attributes:
      label: 问题描述
      description: |
        详细描述你要汇报的问题
        提供详细的信息能让我们更快地处理问题
      placeholder: 只说"不能用"没法让开发者定位问题。
    validations:
      required: true

  - type: input
    id: minecraft-version
    attributes:
      label: Minecraft 版本
      description: 请填写你的 Minecraft 版本
    validations:
      required: true

  - type: textarea
    id: slimefun-version
    attributes:
      label: Slimefun版本
      description: |
        请填写Slimefun版本
        (例如 v4.9-canary-08120db)
        如果你有管理员权限，建议运行`/sf versions`指令，截图并在此上传指令输出的**所有内容**。
    validations:
      required: true

  - type: input
    id: version-plugin
    attributes:
      label: 插件版本
      description: |
        请填写插件版本
